# Generated by Django 4.2.2 on 2023-06-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globaldata', '0004_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='spam_count',
            field=models.IntegerField(default=0),
        ),
    ]
